# Generated by Django 5.2.14 on 2026-05-25 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_projectaccesspath'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('error', 'Error')], default='running', max_length=20)),
                ('goal', models.TextField()),
                ('evaluation_criteria', models.JSONField(blank=True, default=list)),
                ('initial_plan_summary', models.TextField(blank=True)),
                ('current_plan_queue', models.JSONField(blank=True, default=list)),
                ('plan_history', models.JSONField(blank=True, default=list)),
                ('replan_history', models.JSONField(blank=True, default=list)),
                ('final_message', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs_as_assistant', to='agent.message')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='agent.thread')),
                ('user_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs_as_user', to='agent.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentTaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('tool', models.CharField(max_length=40)),
                ('purpose', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], max_length=20)),
                ('input_before', models.TextField(blank=True)),
                ('input_after', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_records', to='agent.agentrun')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('run', 'sequence'), name='unique_agent_task_sequence')],
            },
        ),
    ]
